#.streamlit/secrets.toml

OPENAI_API_KEY="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"
